CREATE TABLE [dbo].[User](
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[UserName] NVARCHAR(50) NOT NULL, 
    [Password] NVARCHAR(MAX) NOT NULL, 
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)
)